import { describe, expect, it } from 'vitest';
import { ARGON2_PARAMS, hashPassword, verifyPassword } from '../modules/auth/passwords.js';

// Generated by the previous native `argon2@0.44.0` implementation with a
// deterministic test-only salt. This guards deployed-user hash compatibility.
const LEGACY_NATIVE_HASH =
  '$argon2id$v=19$m=19456,t=3,p=1$ABEiM0RVZneImaq7zN3u/w$0DPnJmi4r/By9qqk/9+L1BZa9gN3Sr/VJOkuUg8prhU';

describe('password hashing portability', () => {
  it('verifies hashes created by the previous native Argon2 implementation', async () => {
    await expect(verifyPassword(LEGACY_NATIVE_HASH, 'compatibility-password-1')).resolves.toBe(
      true,
    );
    await expect(verifyPassword(LEGACY_NATIVE_HASH, 'wrong-password')).resolves.toBe(false);
  });

  it('creates standard Argon2id hashes with the approved parameters', async () => {
    const hash = await hashPassword('new-password-1');

    expect(hash).toMatch(
      new RegExp(
        `^\\$argon2id\\$v=19\\$m=${ARGON2_PARAMS.memoryCost},t=${ARGON2_PARAMS.timeCost},p=${ARGON2_PARAMS.parallelism}\\$`,
      ),
    );
    await expect(verifyPassword(hash, 'new-password-1')).resolves.toBe(true);
    await expect(verifyPassword(hash, 'wrong-password')).resolves.toBe(false);
  });

  it('fails closed for malformed stored hashes', async () => {
    await expect(verifyPassword('not-a-valid-hash', 'password')).resolves.toBe(false);
  });
});
